### ISSUE TITLE
Trying to run on my IOS phone via Expo Go

### ISSUE THREAD

**Issue by ChazKat** [kenhawkins13/Danganronpa-Werewolf-GM-App#1]
![IMG_4399](https://user-images.githubusercontent.com/76671981/221307598-b8a0f165-2d21-4459-88de-c038cf0e6e39.PNG)

So I had two issues come up during trying to run this app off my mac terminal onto my Iphone. The first one had to do with the Revolver.mp3 being named with a lowercase r instead of a capital one, I repaired that and tried again and ended up with this error which I can't seem to figure out

**Comment by ChazKat** [comment]
Also it seems to crash whenever I try to run it on an android emulator on my computer, it does this after monokuma begins his announcement

**Comment by kenhawkins13** [comment]
The error in your screenshot might be the same as this error: https://github.com/teambit/envs/issues/143

Can you try their solution? 

This stackoverflow [question ](https://stackoverflow.com/questions/60124435/however-this-package-itself-specifies-a-main-module-field-that-could-not-be-r) has the same answer. However, the 2nd answer was to simply restart the terminal. You can try that too.

**Comment by ChazKat** [comment]
Wow I can't believe I actually got this working, thank you so much! It looks like the only real issue was the revolver file name, the other one I just had to reset the terminal. Again thank you so much

**Comment by kenhawkins13** [comment]
Awesome! Glad to hear it just needed a restart.

Also, I renamed `revolver.mp3` to `Reolver.mp3`. Weirdly on my machine, it had the proper case but for some reason, it couldn't recognize that on github, the name was all lowercase. So had to do some hacky name changing to fix that.

Thanks for pointing out the issue.
